### ISSUE TITLE
launchdarkly plagin exited with exit status 2

### ISSUE THREAD

**Issue by Ri0n** [terraform-providers/terraform-provider-launchdarkly#23]
Hi
during terraform plan it starts handling the flags (75 flags + 4 per environement configuration with fallthrough to default variation setting for all them), but somewhere in the middle I get this:

```
Error: rpc error: code = Canceled desc = context canceled



Error: rpc error: code = Unavailable desc = transport is closing


Releasing state lock. This may take a few moments...
2020-04-21T18:31:00.592+0300 [DEBUG] plugin.terraform-provider-launchdarkly_v1.2.1_x4: 
2020-04-21T18:31:00.592+0300 [DEBUG] plugin.terraform-provider-launchdarkly_v1.2.1_x4: goroutine 189 [running]:
2020-04-21T18:31:00.592+0300 [DEBUG] plugin.terraform-provider-launchdarkly_v1.2.1_x4: github.com/terraform-providers/terraform-provider-launchdarkly/launchdarkly.targetsToResourceData(0xc00060a300, 0x1, 0x4, 0xeb5ce0, 0xc0005bcf60)
2020-04-21T18:31:00.592+0300 [DEBUG] plugin.terraform-provider-launchdarkly_v1.2.1_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-launchdarkly/launchdarkly/target_helper.go:62 +0x1ef
2020-04-21T18:31:00.592+0300 [DEBUG] plugin.terraform-provider-launchdarkly_v1.2.1_x4: github.com/terraform-providers/terraform-provider-launchdarkly/launchdarkly.resourceFeatureFlagEnvironmentRead(0xc00031b500, 0xe98b40, 0xc0001384c0, 0xc00031b500, 0x0)
2020-04-21T18:31:00.592+0300 [DEBUG] plugin.terraform-provider-launchdarkly_v1.2.1_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-launchdarkly/launchdarkly/resource_launchdarkly_feature_flag_environment.go:171 +0x761
2020-04-21T18:31:00.592+0300 [DEBUG] plugin.terraform-provider-launchdarkly_v1.2.1_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000169300, 0xc00076b2c0, 0xe98b40, 0xc0001384c0, 0xc00052ed80, 0x0, 0x0)
2020-04-21T18:31:00.592+0300 [DEBUG] plugin.terraform-provider-launchdarkly_v1.2.1_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-launchdarkly/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:455 +0x119
2020-04-21T18:31:00.592+0300 [DEBUG] plugin.terraform-provider-launchdarkly_v1.2.1_x4: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00016e590, 0x12e5060, 0xc0005d7e00, 0xc00076b1d0, 0xc00016e590, 0xc0005d7e00, 0xc000219bd0)
2020-04-21T18:31:00.592+0300 [DEBUG] plugin.terraform-provider-launchdarkly_v1.2.1_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-launchdarkly/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:525 +0x3d7
2020-04-21T18:31:00.592+0300 [DEBUG] plugin.terraform-provider-launchdarkly_v1.2.1_x4: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x10438c0, 0xc00016e590, 0x12e5060, 0xc0005d7e00, 0xc000441080, 0x0, 0x12e5060, 0xc0005d7e00, 0xc0002de900, 0x11b)
2020-04-21T18:31:00.592+0300 [DEBUG] plugin.terraform-provider-launchdarkly_v1.2.1_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-launchdarkly/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3153 +0x23e
2020-04-21T18:31:00.592+0300 [DEBUG] plugin.terraform-provider-launchdarkly_v1.2.1_x4: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003c0160, 0x12f0d00, 0xc000001980, 0xc0006a3000, 0xc00039ecc0, 0x1ae8230, 0x0, 0x0, 0x0)
2020-04-21T18:31:00.592+0300 [DEBUG] plugin.terraform-provider-launchdarkly_v1.2.1_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-launchdarkly/vendor/google.golang.org/grpc/server.go:995 +0x466
2020-04-21T18:31:00.592+0300 [DEBUG] plugin.terraform-provider-launchdarkly_v1.2.1_x4: google.golang.org/grpc.(*Server).handleStream(0xc0003c0160, 0x12f0d00, 0xc000001980, 0xc0006a3000, 0x0)
2020-04-21T18:31:00.592+0300 [DEBUG] plugin.terraform-provider-launchdarkly_v1.2.1_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-launchdarkly/vendor/google.golang.org/grpc/server.go:1275 +0xda6
2020-04-21T18:31:00.592+0300 [DEBUG] plugin.terraform-provider-launchdarkly_v1.2.1_x4: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00015a240, 0xc0003c0160, 0x12f0d00, 0xc000001980, 0xc0006a3000)
2020-04-21T18:31:00.592+0300 [DEBUG] plugin.terraform-provider-launchdarkly_v1.2.1_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-launchdarkly/vendor/google.golang.org/grpc/server.go:710 +0x9f
2020-04-21T18:31:00.592+0300 [DEBUG] plugin.terraform-provider-launchdarkly_v1.2.1_x4: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-04-21T18:31:00.592+0300 [DEBUG] plugin.terraform-provider-launchdarkly_v1.2.1_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-launchdarkly/vendor/google.golang.org/grpc/server.go:708 +0xa1
2020-04-21T18:31:00.594+0300 [DEBUG] plugin: plugin process exited: path=/home/rion/work/ms/deploy/terraform/launchdarkly/.terraform/plugins/linux_amd64/terraform-provider-launchdarkly_v1.2.1_x4 pid=9136 error="exit status 2"
```
$ terraform --version
Terraform v0.12.24
+ provider.aws v2.58.0
+ provider.launchdarkly v1.2.1

I can provide any additional information if required but not sure if here.

**Comment by ldhenry** [comment]
Hi @Ri0n,

This is a tricky one. I've created an internal ticket to take a deeper look. In the meantime, it would be helpful if you could send along you `resource_launchdarkly_feature_flag_environment` configurations (obfuscated if there is sensitive data).

Thanks,
Henry

**Comment by Ri0n** [comment]
Ok, stripped my configs to just one flag and removed this fallthrough since it wasn't used before. the problem is still reproducible.

Slightly obfuscated version of the above
```
resource "launchdarkly_feature_flag" "general_refresh_period" {
  project_key    = launchdarkly_project.rtcp.key
  key            = "myprefix.general.refresh_period"
  name           = "general.refresh_period"
  variation_type = "number"

  variations {
    value      = "30000"
    name       = "30s"
  }

  variations {
    value      = "60000"
    name       = "60s"
  }

  tags = ["terraform", "mytag1", "mytag2"]
}
resource "launchdarkly_feature_flag_environment" "general_refresh_period_ci" {
  flag_id           = launchdarkly_feature_flag.general_refresh_period.id
  env_key           = launchdarkly_environment.ci.key
  targeting_enabled = false
}
resource "launchdarkly_feature_flag_environment" "general_refresh_period_gamedev" {
  flag_id           = launchdarkly_feature_flag.general_refresh_period.id
  env_key           = launchdarkly_environment.gamedev.key
  targeting_enabled = false
}
resource "launchdarkly_feature_flag_environment" "general_refresh_period_prod" {
  flag_id           = launchdarkly_feature_flag.general_refresh_period.id
  env_key           = launchdarkly_environment.prod.key
  targeting_enabled = false
}
resource "launchdarkly_feature_flag_environment" "general_refresh_period_test" {
  flag_id           = launchdarkly_feature_flag.general_refresh_period.id
  env_key           = launchdarkly_environment.test.key
  targeting_enabled = false
}
```

All the resources are in different files. First is the major one and others are per environment.

But I believe if it's still reproducible with this minimal example the problem is in something else.
Maybe it can't build proper plan for already existing in LaunchDarkly/state flags.

**Comment by ldhenry** [comment]
Your theory "Maybe it can't build proper plan for already existing in LaunchDarkly/state flag" seems reasonable. For resources that already exists you'll have to run a `terraform import` first. However, I still want to investigate this further because we should at least be returning a more friendly error message.

**Comment by ldhenry** [comment]
Hi @Ri0n,

Because of your help I was finally able to reproduce and fix this bug. If you update your provider to version 1.2.2 you should no longer see this issue.

Thanks,
Henry
